name: Reusable Testing Workflow (with uv and PostgreSQL)

on:
  workflow_call:
    inputs:
      pytest_flags:
        description: "Flags to run with pytest"
        required: false
        default: ''
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Build docker container
        run: |
          docker compose up --build -d
      - name: Wait for container to be ready
        run: |
          sleep 10

      - name: Run tests
        run: |
          docker exec paytrack uv run pytest ${{ inputs.pytest_flags }}

      - name: Stop and remove container
        run: docker compose down --volumes
